config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#root'

  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create' # Needed for developer strategy

  delete '/sessions', to: 'sessions#destroy', as: :logout

  resources :messages, only: %i(index)
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user

  after_commit { CommentRelayJob.perform_later(self) }
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  scope :current, -> { order(created_at: :desc).limit(5) }

  def as_json(options = {})
    MessageSerializer.new(self).as_json
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  validates :provider, :name, :uid, presence: true

  def self.find_or_create_from_auth_hash(auth_hash)
    User.find_or_create_by!({provider: auth_hash['provider'],
                             uid: auth_hash['uid'],
                             name: auth_hash['info']['name']})
  end

  def as_json(options = {})
    options.reverse_merge!({
      only: :uid
    })
    super(options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :find_current_user
  attr_reader :current_user
  helper_method :current_user

  private

  def find_current_user
    return unless cookies.signed[:user_id]
    @current_user = User.find_by(id: cookies.signed[:user_id])
  end

  def require_current_user
    redirect_to '/auth/developer' unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_message

  def create
    @comment = Comment.create! content: params[:comment][:content], message: @message, user: @current_user
  end

  private
    def set_message
      @message = Message.find(params[:message_id])
    end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern
  
  included do
    before_action :ensure_authenticated_user
  end

  private
    def ensure_authenticated_user
      authenticate_user(cookies.signed[:user_id]) || redirect_to(new_session_url)
    end

    def authenticate_user(user_id)
      if authenticated_user = User.find_by(id: user_id)
        cookies.signed[:user_id] ||= user_id
        @current_user = authenticated_user
      end
    end

    def unauthenticate_user
      ActionCable.server.disconnect(current_user: @current_user)
      @current_user = nil
      cookies.delete(:user_id)
    end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_current_user

  def index
    @current_messages = Message.current.includes(:user).reverse
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_current_user

  def root
    redirect_to messages_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create # Needed for developer strategy

  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    cookies.signed[:user_id] = user.id
    redirect_to messages_path
  end

  def destroy
    cookies.signed[:user_id] = nil
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<article data-user-id="<%= comment.user.id %>">
  <h3>Comment by <%= comment.user.name %></h3>
  <p><%= comment.content %></p>
</article>

app/views/comments/_comments.html.erb
<section id="comments" data-channel="comments" data-message-id="<%= message.id %>">
  <%= render message.comments %>
</section>

<%= render 'comments/new', message: message %>

app/views/comments/_new.html.erb
<%= form_for [ message, Comment.new ], remote: true do |form| %>
  <%= form.text_area :content, size: '100x20' %><br>
  <%= form.submit 'Post comment' %>
<% end %>

app/views/comments/create.js.erb
$('#comments').append('<%=j render @comment %>');
$('#new_comment').replaceWith('<%=j render 'comments/new', message: @message %>');

app/views/examples/index.html.erb
<h1>Action Cable Examples</h1>

<p>
  Hello <%= @current_user.name %>
  (<%= link_to 'Logout', session_path, method: :delete %>)!
</p>

<ul>
  <li><%= link_to 'Messages with live comments', messages_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActioncableChat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <% if current_user %>
    <%= link_to 'Sign Out', logout_path, method: :delete %>
  <% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<div id="emojis">

  <span class="emoji">🚽</span>
  <span class="emoji">🚀</span>
  <span class="emoji">🚲</span>
  <span class="emoji">🚗</span>
  <span class="emoji">⏰</span>
</div>


<textarea id="hint"></textarea>


<div id='messages'>
  <ul id='messages-list'>
    <% @current_messages.each do |message| %>
        <li class='messages-list-item'>
          <div class='messages-list-item-name'>
            <%= message.user.uid %>:

            <div class='messages-list-item-timestamp'>
              (<%= l message.created_at, format: :short %>)
            </div>
          </div>
          <div class='messages-list-item-body'>
            <%= message.body %>

          </div>
        </li>
    <% end %>
  </ul>
</div>

<div id='message-form-wrapper'>
  <%= form_for :message, url: '#post-message', html: {id: 'message-form'} do |f| %>
      <%= f.text_area :body, id: 'message-form-body' %>
      <%= f.submit id: 'message-form-submit' %>
  <% end %>
</div>

app/views/messages/show.html.erb
<h1><%= @message.title %></h1>

<p><%= @message.content %></p>

<%= render 'comments/comments', message: @message %>